name: 'LFS asset resolver'
description: 'Takes a set of Git LFS pointer files, resolves their original URL and invokes an processor Lambda on each key to create a set of output images'
runs:
  using: 'node16'
  main: 'dist/index.js'
inputs:
  muse_product_slug:
    description: 'Product slug path to use for image uploads, may include a commit SHA for versioning'
    required: true
  aws_s3_bucket:
    description: 'Target bucket for image uploads'
    required: true
  lambda_target:
    description: 'The AWS Lambda function to invoke for each image pointer'
    required: false
    default: 'muse-create-preview-lfs'
  repository:
    description: 'The Github repository where the Action is running'
    required: true
  lfs_discovery_endpoint:
    description: 'Git LFS API path for image discovery'
    required: true
  source_dir:
    description: 'Project directory where source images are located. Internally the resolver looks within this for an `images` folder'
    required: false
    default: 'static-assets'
  modified_images:
    description: A list of the modified images in a given range of commits
    required: false
  print_image_dpi:
    description: 'Pixel resolution of a print image'
    required: false
    default: 300
  preview_image_dpi:
    description: 'Pixel resolution of a preview image'
    required: false
    default: 72
