name: 'LFS asset resolver'
description: 'Takes a set of Git LFS pointer files, resolves their original URL and invokes an processor Lambda on each key to create a set out of output images'
runs:
  using: 'node12'
  main: 'dist/index.js'
